global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: "railway-prom"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9090"]

  # - job_name: "postgres"
  #   scrape_interval: 15s
  #   static_configs:
  #     - targets: ["roundhouse.proxy.rlwy.net:38862"]

  # - job_name: "indexer"
  #   scrape_interval: 15s
  #   static_configs:
  #     - targets: ["demo.do.prometheus.io:9090"]

  # - job_name: "hasura_prometheus_exporter"
  #   scrape_interval: 60s ## Recommended scrape interval is 60s
  #   metrics_path: "/metrics" ## Replace with metrics Path of the connection URL
  #   scheme: "https" ## Replace with the scheme of the connection URL
  #   basic_auth:
  #     username: "" ## Replace with project ID
  #     password: "" ## Replace with Access Token
  #   static_configs:
  #     - targets: ["graph-api.themetadao.org"]
